# Generated by Django 5.0.6 on 2024-06-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('author', models.TextField(verbose_name='Автор')),
                ('views_count', models.IntegerField(verbose_name='Количество просмотров')),
                ('ad_position', models.IntegerField(verbose_name='Позиция в списке')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
